import img from '../assets/image/ip1.png'
export const comparison = [
    {
        id:1,
        img:img,
        name:'Смартфоны',
        title:'Apple iPhone 13 Pro Max 256 ГБ серый',
        price:'114 099 ₽',
        rating:1,
        people:447,
        model:'Apple iPhone 13 Pro Max',
        year:2021,
        yader:12,
        lte:true,
        ram:'128 ГБ',
    },
    {
        id:2,
        img:img,
        name:'Смартфоны',
        title:'Apple iPhone 13 Pro Max 256 ГБ красный',
        price:'114 099 ₽',
        rating:2,
        people:100,
        model:'Apple iPhone 13 Pro Max',
        year:2021,
        yader:12,
        lte:true,
        ram:'64 ГБ',
    },
    {
        id:3,
        img:img,
        name:'Смартфоны',
        title:'Apple iPhone 13 Pro Max 256 ГБ черный',
        price:'114 099 ₽',
        rating:3,
        people:200,
        model:'Apple iPhone 12 Pro Max',
        year:2021,
        yader:6,
        lte:true,
        ram:'64 ГБ',
    },


]