import img from '../assets/image/imgip.png'
import img1 from '../assets/image/ipmax.png'
export const productInfo = [
    {
        id: 1,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',

        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        description: 'Смартфон Apple iPhone 13 выполнен в компактном корпусе с привлекательной розовой расцветкой и защищенной ' +
            'конструкцией по стандарту IP68. Мощный чип A15 Bionic обеспечивает быструю и стабильную работу при запуске приложений,' +
            ' просмотре видео, веб-серфинге и выполнении других задач. На дисплее 6.1 дюйма OLED выводится четкая и красочная картинка.\n' +
            'На тыловой стороне расположена камера с двумя датчиками по 12 Мп, которые при поддержке ряда технологий и функций позволяют ' +
            'создавать реалистичные снимки в различных условиях. На передней стороне имеется камера 12 Мп для селфи и общения. В мобильном ' +
            'устройстве предлагается широкий набор беспроводных интерфейсов и разъем Lightning 8-pin. Аккумулятор гарантирует' +
            ' продолжительное время автономности. Из особенностей отмечаются поддержка быстрой зарядки, беспроводной зарядки и устройств' +
            ' MagSafe с магнитным позиционированием.',
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },

    {
        id: 2,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
    {
        id: 3,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
    {
        id: 4,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
    {
        id: 6,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
    {
        id: 7,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
    {
        id: 8,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
    {
        id: 9,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
    {
        id: 10,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
    {
        id: 1,
        img: img,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        }
    },
]