import img from '../assets/image/imgip.png'
import img1 from '../assets/image/ipmax.png'
export const productInfo = [
    {
        id: 1,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
    {
        id: 2,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 127,
        title: 'Apple iPhone 13 Pro Max 128 ГБ красный',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '75 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 2,
            batar: 4,
            display: 5,
            camera: 2,
            otvet: 3,
            port: 4
        },
        camera:'128 MPx',
        sistem:'iOS',
        diog:'6,4”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 12',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
    {
        id: 3,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
    {
        id: 4,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
    {
        id: 5,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
    {
        id: 6,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
    {
        id: 7,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
    {
        id: 8,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
    {
        id: 9,
        img1: img,
        img2: img,
        img3: img,
        imgMax:img1,
        osenka: 4.4,
        rating: 4.0,
        otziv: 447,
        title: 'Apple iPhone 13 Pro Max 256 ГБ серый',
        sim: true,
        display: true,
        bionic: true,
        mpcam: true,
        ram: true,
        memory: false,
        mah: true,
        ios: true,
        price: '78 999 ₽',
        procent: '13%',
        colors:{
            white:'#F2F5F9',
            yellow:'#FFE0BB',
            red:'#FFBBBB',
            black:'#6C6C6C',
            green:'#BBFFE2',
            blue:'#BBC2FF',
            orange:'#FEBBFF'
        },
        memores:{
            ram1:'128 ГБ',
            ram2:'256 ГБ',
            ram3:'512 ГБ'
        },
        info: {
            desing: 4,
            batar: 2,
            display: 4,
            camera: 5,
            otvet: 5,
            port: 4
        },
        camera:'48 MPx',
        sistem:'iOS',
        diog:'6,1”',
        charge:'Беспроводная',
        tip:'смартфон',
        model:'Apple iPhone 13',
        year:2021,
        razcamer:'50 мг',
        pixel:'457 ppi',
        ekran:'OLED',
        colorSum:'16.7 млн',
        constEkran:'безрамочный, вырез на экране',

    },
]